### ISSUE TITLE
Factor given by creation does not work

### ISSUE THREAD

**Issue by Nico96R** [hubtub2/ha_custom_components#4]
Hi,
regarding: sensor.py
I recognized, that the factor in line 73 is not used. It shows me the same in kWh like in kg from the "used pellets". I think the factor given by the creation call is not used. Maybe line 112 is overwriting the value.
In my eta PU15 I have found the following value, this might be the right one for that.
`/user/var//40/10021/14877/0/2273`

Thank you for the integration!

**Comment by zypro** [comment]
You're right about the factor. The 4.8 kWh is the energy density of pellets. I'll try to figure out why the factor isn't used correctly.

Your suggested variable is maybe not the wohle energy consumption because its only the energy of the heating part and not warm water. So it might be the better idea to use the pellet usage and multiply it with 4.8 kWh.
What do you think?

**Comment by zypro** [comment]
fixed in https://github.com/hubtub2/ha_custom_components/pull/6

**Comment by zypro** [comment]
@Nico96R I fixed it. Either you change the code yourself or you copy my fork until @hubtub2 merges the PR.

**Comment by hubtub2** [comment]
I have merged the PR - thanks for you contribution - stupid bug by me :-)
